-- Create password_reset_requests table for secure password reset flow
-- Users request password reset → Admin approves → Temp password generated → Admin sends to user

CREATE TABLE IF NOT EXISTS password_reset_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mobile text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  requested_at timestamp NOT NULL DEFAULT now(),
  approved_at timestamp,
  temp_password text,
  CONSTRAINT fk_user_mobile FOREIGN KEY (mobile) REFERENCES users(mobile) ON DELETE CASCADE
);

-- Create index for faster lookups
CREATE INDEX idx_password_reset_mobile ON password_reset_requests(mobile);
CREATE INDEX idx_password_reset_status ON password_reset_requests(status);

-- Add comment for documentation
COMMENT ON TABLE password_reset_requests IS 'Stores password reset requests that require admin approval for security';
COMMENT ON COLUMN password_reset_requests.status IS 'pending: awaiting admin review, approved: temp password generated, rejected: request denied';
COMMENT ON COLUMN password_reset_requests.temp_password IS 'Temporary password generated by admin, stored for admin reference only';
