-- Fix all remaining data type issues
-- Run this in Supabase SQL Editor to fix all problematic columns

ALTER TABLE glomar_properties 
  ALTER COLUMN created_at TYPE TEXT,
  ALTER COLUMN updated_at TYPE TEXT,
  ALTER COLUMN building TYPE TEXT,
  ALTER COLUMN propertynumber TYPE TEXT,
  ALTER COLUMN thefloors TYPE TEXT,
  ALTER COLUMN unitfeatures TYPE TEXT,
  ALTER COLUMN phase TYPE TEXT,
  ALTER COLUMN inoroutsidecompound TYPE TEXT,
  ALTER COLUMN lastfollowin TYPE TEXT,
  ALTER COLUMN status TYPE TEXT,
  ALTER COLUMN propertyofferedby TYPE TEXT,
  ALTER COLUMN name TYPE TEXT,
  ALTER COLUMN unitno TYPE TEXT,
  ALTER COLUMN callupdate TYPE TEXT,
  ALTER COLUMN handler TYPE TEXT,
  ALTER COLUMN sales TYPE TEXT,
  ALTER COLUMN modifiedtime TYPE TEXT,
  ALTER COLUMN landarea TYPE TEXT,
  ALTER COLUMN rentfrom TYPE TEXT,
  ALTER COLUMN rentto TYPE TEXT,
  ALTER COLUMN compoundname TYPE TEXT,
  ALTER COLUMN mobileno TYPE TEXT,
  ALTER COLUMN tel TYPE TEXT,
  ALTER COLUMN project TYPE TEXT,
  ALTER COLUMN payedevery TYPE TEXT,
  ALTER COLUMN monthly TYPE TEXT,
  ALTER COLUMN createdtime TYPE TEXT,
  ALTER COLUMN region_id_new TYPE TEXT,
  ALTER COLUMN property_type_id_new TYPE TEXT,
  ALTER COLUMN finishing_level_id_new TYPE TEXT,
  ALTER COLUMN currency_id_new TYPE TEXT,
  ALTER COLUMN category_id_new TYPE TEXT,
  ALTER COLUMN unit_facility_id_new TYPE TEXT,
  ALTER COLUMN region_name TYPE TEXT,
  ALTER COLUMN country_name TYPE TEXT,
  ALTER COLUMN property_type_name TYPE TEXT,
  ALTER COLUMN _databaseid TYPE TEXT,
  ALTER COLUMN _collectionid TYPE TEXT;

-- Drop foreign key constraint temporarily (will recreate after migration if needed)
ALTER TABLE glomar_properties DROP CONSTRAINT IF EXISTS glomar_properties_project_fkey;
