@echo off
REM Appwrite Deployment Script for Windows
REM Reallisting Platform

echo ========================================
echo   Appwrite Deployment Script (Windows)
echo ========================================
echo.

REM Configuration
set PROJECT_ID=694ba83300116af11b75
set ENDPOINT=https://fra.cloud.appwrite.io/v1
set DATABASE_ID=reallisting

echo Configuration:
echo   Project ID: %PROJECT_ID%
echo   Endpoint: %ENDPOINT%
echo   Database ID: %DATABASE_ID%
echo.

REM Check for API key
if "%APPWRITE_API_KEY%"=="" (
    echo [ERROR] APPWRITE_API_KEY environment variable not set
    echo.
    echo To set your API key:
    echo   1. Go to Appwrite Console -^> Project Settings -^> API Keys
    echo   2. Create a new API key with all permissions
    echo   3. Run: set APPWRITE_API_KEY=your-api-key
    echo.
    exit /b 1
)

echo [OK] API key found
echo.

REM Step 1: Install dependencies
echo [Step 1/5] Installing dependencies...
call npm install
if errorlevel 1 (
    echo [ERROR] Failed to install dependencies
    exit /b 1
)
echo [OK] Dependencies installed
echo.

REM Step 2: Setup database
echo [Step 2/5] Setting up Appwrite database...
node scripts\setup-appwrite-db.js
if errorlevel 1 (
    echo [ERROR] Database setup failed
    exit /b 1
)
echo [OK] Database setup complete
echo.

REM Step 3: Build React app
echo [Step 3/5] Building React application...
call npm run build
if errorlevel 1 (
    echo [ERROR] Build failed
    exit /b 1
)
echo [OK] React app built successfully
echo.

REM Step 4: Instructions for deployment
echo [Step 4/5] Deployment Instructions
echo.
echo Your application is ready for deployment!
echo.
echo Static Files:
echo   - Location: build\ directory
echo   - Deploy to: Appwrite Storage or static hosting (Netlify/Vercel)
echo.
echo API Functions:
echo   - Location: api\*-appwrite.js
echo   - Deploy via Appwrite Console -^> Functions
echo   - Or use Netlify/Vercel serverless functions
echo.

REM Step 5: Create .env file
echo [Step 5/5] Creating environment file...
(
echo # Appwrite Configuration - Generated by deploy script
echo APPWRITE_ENDPOINT=%ENDPOINT%
echo APPWRITE_PROJECT_ID=%PROJECT_ID%
echo APPWRITE_DATABASE_ID=%DATABASE_ID%
echo APPWRITE_API_KEY=%APPWRITE_API_KEY%
echo.
echo # React App Environment Variables
echo REACT_APP_APPWRITE_ENDPOINT=%ENDPOINT%
echo REACT_APP_APPWRITE_PROJECT_ID=%PROJECT_ID%
echo REACT_APP_APPWRITE_DATABASE_ID=%DATABASE_ID%
) > .env

echo [OK] Environment file created
echo.

echo ========================================
echo   Deployment Complete!
echo ========================================
echo.
echo Next Steps:
echo.
echo 1. Deploy Static Files:
echo    - Upload 'build' folder to your hosting provider
echo    - Recommended: Netlify or Vercel for easy deployment
echo.
echo 2. Deploy API Functions:
echo    - Use Netlify/Vercel for serverless functions, OR
echo    - Deploy to Appwrite Functions (requires manual setup)
echo.
echo 3. Configure Environment Variables:
echo    - In your hosting dashboard, add variables from .env file
echo.
echo 4. Test your deployment:
echo    - Visit your deployed URL
echo    - Try logging in and creating listings
echo.
echo Documentation:
echo    - Netlify: https://www.netlify.com/
echo    - Vercel: https://vercel.com/
echo    - Appwrite: https://appwrite.io/docs
echo.
pause
